dsm_server : dsm_server.h  dsm_server.cc  Dsm_msg.h Dsm_msg.o  
	c++   -g -o dsm_server dsm_server.cc  ../C_mach_interface.o Dsm_msg.o

Dsm_msg.o : Dsm_msg.h Dsm_msg.cc
	c++  -g -c Dsm_msg.cc 


test_server : test_server.cc Dsm_msg.h Dsm_msg.h
	c++ -o test_server test_server.cc ../C_mach_interface.o Dsm_msg.o \
	../dsm_region.o
	strip test_server

